[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd sales-scorecard-api && npm ci"]

[phases.build]
cmds = ["cd sales-scorecard-api && npx prisma generate"]

[start]
cmd = "cd sales-scorecard-api && npm run start:dev"