[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = [
  "rm -rf node_modules/.prisma",
  "rm -rf node_modules/@prisma",
  "npx prisma generate",
  "npx tsc"
]

[start]
cmd = "npm run start"