[phases.setup]
nixPkgs = ["nodejs_18", "npm-9_x", "openssl"]

[phases.install]
cmds = ["npm ci"]

[phases.build]
cmds = ["npx prisma generate", "npx tsc"]

[phases.start]
cmd = "npm install pg @types/pg && chmod +x start.sh && ./start.sh"
